### ISSUE TITLE
Armadillo required

### ISSUE THREAD

**Issue by chia-labradorsystems** [songshan0321/ros_vino#2]
First of all, thx for your contribution.
works much smoother than intel's one :P

Secondly, I find out you set armadillo for requirement, but only for tracking
I suggest you separate the sample program to another package.

Or, include the Armadillo installation steps on Readme.md
`sudo apt-get install libarmadillo-dev`

Again, thx for your effort, Good Job :)

**Comment by songshan0321** [comment]
Thanks for pointing out my Armadillo dependency. I have updated it in README.md. I will also consider to separate the sample program into another package in future updates. 

Also, thanks for your encouragement! =D
@chia-labradorsystems
